[workspace]
resolver = "2"
members = [
    "angel-sm",
    "angel",
    "heaven",
    "common",
    "config",
    "octhulhu-agent", "cthulhu-netbox", "cthulhu-provision",
]

default-members = [
    "angel",
    "heaven",
]

[profile.release]
#debug = true
